version: '3.2'
services:
  sqlserver:
    build: ./sql_server
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - PGDATA=/data
    volumes:
      - type: bind
        source: ./data
        target: /data
  webapp:
    build: ./main
    ports:
      - "800:80"